// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package taskmanager

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

//Define some common types for our service.
//Thrift ensures that different languages serialize these type definitions to appropriate
//language-specific types.
type ID int64

func IDPtr(v ID) *ID { return &v }

type Int int32

func IntPtr(v Int) *Int { return &v }

// structs are mapped by Thrift to classes or structs in your language of
// choice. This struct has two fields, an Identifier of type `id` and
// a Description of type `string`. The Identifier defaults to DEFAULT_ID.
// 
// Attributes:
//  - Identifier: A unique identifier for this task.
//  - Description: A description of the task.
type Task struct {
  Identifier ID `thrift:"Identifier,1" db:"Identifier" json:"Identifier"`
  Description string `thrift:"Description,2" db:"Description" json:"Description"`
}

func NewTask() *Task {
  return &Task{
Identifier: -1,
}
}


func (p *Task) GetIdentifier() ID {
  return p.Identifier
}

func (p *Task) GetDescription() string {
  return p.Description
}
func (p *Task) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *Task)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := ID(v)
  p.Identifier = temp
}
  return nil
}

func (p *Task)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Description = v
}
  return nil
}

func (p *Task) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "Task"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *Task) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "Identifier", thrift.I64, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:Identifier: ", p), err) }
  if err := oprot.WriteI64(ctx, int64(p.Identifier)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.Identifier (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:Identifier: ", p), err) }
  return err
}

func (p *Task) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "Description", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:Description: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.Description)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.Description (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:Description: ", p), err) }
  return err
}

func (p *Task) Equals(other *Task) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.Identifier != other.Identifier { return false }
  if p.Description != other.Description { return false }
  return true
}

func (p *Task) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("Task(%+v)", *p)
}

func (p *Task) Validate() error {
  return nil
}
// Exceptions inherit from language-specific base exceptions.
// 
// Attributes:
//  - Reason: @ The reason for this exception.
type TaskException struct {
  Reason string `thrift:"Reason,1" db:"Reason" json:"Reason"`
}

func NewTaskException() *TaskException {
  return &TaskException{}
}


func (p *TaskException) GetReason() string {
  return p.Reason
}
func (p *TaskException) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TaskException)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.Reason = v
}
  return nil
}

func (p *TaskException) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "TaskException"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TaskException) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "Reason", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:Reason: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.Reason)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.Reason (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:Reason: ", p), err) }
  return err
}

func (p *TaskException) Equals(other *TaskException) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.Reason != other.Reason { return false }
  return true
}

func (p *TaskException) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TaskException(%+v)", *p)
}

func (p *TaskException) Error() string {
  return p.String()
}

func (TaskException) TExceptionType() thrift.TExceptionType {
  return thrift.TExceptionTypeCompiled
}

var _ thrift.TException = (*TaskException)(nil)

func (p *TaskException) Validate() error {
  return nil
}
type TaskManager interface {  //A service defines the API that is exposed to clients.
  //
  //This TaskManager service has one available endpoint for creating a task.

  // @
  // Create a new task.
  // 
  // This method accepts a Task struct and returns an i64.
  // It may throw a TaskException.
  // 
  // Parameters:
  //  - Task
  Create(ctx context.Context, task *Task) (_r int64, _err error)
}

//A service defines the API that is exposed to clients.
//
//This TaskManager service has one available endpoint for creating a task.
type TaskManagerClient struct {
  c thrift.TClient
  meta thrift.ResponseMeta
}

func NewTaskManagerClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *TaskManagerClient {
  return &TaskManagerClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewTaskManagerClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *TaskManagerClient {
  return &TaskManagerClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewTaskManagerClient(c thrift.TClient) *TaskManagerClient {
  return &TaskManagerClient{
    c: c,
  }
}

func (p *TaskManagerClient) Client_() thrift.TClient {
  return p.c
}

func (p *TaskManagerClient) LastResponseMeta_() thrift.ResponseMeta {
  return p.meta
}

func (p *TaskManagerClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
  p.meta = meta
}

// @
// Create a new task.
// 
// This method accepts a Task struct and returns an i64.
// It may throw a TaskException.
// 
// Parameters:
//  - Task
func (p *TaskManagerClient) Create(ctx context.Context, task *Task) (_r int64, _err error) {
  var _args0 TaskManagerCreateArgs
  _args0.Task = task
  var _result2 TaskManagerCreateResult
  var _meta1 thrift.ResponseMeta
  _meta1, _err = p.Client_().Call(ctx, "create", &_args0, &_result2)
  p.SetLastResponseMeta_(_meta1)
  if _err != nil {
    return
  }
  switch {
  case _result2.E!= nil:
    return _r, _result2.E
  }

  return _result2.GetSuccess(), nil
}

type TaskManagerProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler TaskManager
}

func (p *TaskManagerProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *TaskManagerProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *TaskManagerProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewTaskManagerProcessor(handler TaskManager) *TaskManagerProcessor {

  self3 := &TaskManagerProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self3.processorMap["create"] = &taskManagerProcessorCreate{handler:handler}
return self3
}

func (p *TaskManagerProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
  if err2 != nil { return false, thrift.WrapTException(err2) }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(ctx, thrift.STRUCT)
  iprot.ReadMessageEnd(ctx)
  x4 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
  x4.Write(ctx, oprot)
  oprot.WriteMessageEnd(ctx)
  oprot.Flush(ctx)
  return false, x4

}

type taskManagerProcessorCreate struct {
  handler TaskManager
}

func (p *taskManagerProcessorCreate) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err5 error
  args := TaskManagerCreateArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "create", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := TaskManagerCreateResult{}
  if retval, err2 := p.handler.Create(ctx, args.Task); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    switch v := err2.(type) {
    case *TaskException:
      result.E = v
    default:
      if errors.Is(err2, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err2)
      }
      if errors.Is(err2, context.Canceled) {
        if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
          return false, thrift.WrapTException(err)
        }
      }
      _exc6 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing create: " + err2.Error())
      if err2 := oprot.WriteMessageBegin(ctx, "create", thrift.EXCEPTION, seqId); err2 != nil {
        _write_err5 = thrift.WrapTException(err2)
      }
      if err2 := _exc6.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
        _write_err5 = thrift.WrapTException(err2)
      }
      if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
        _write_err5 = thrift.WrapTException(err2)
      }
      if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
        _write_err5 = thrift.WrapTException(err2)
      }
      if _write_err5 != nil {
        return false, thrift.WrapTException(_write_err5)
      }
      return true, err
    }
  } else {
    result.Success = &retval
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "create", thrift.REPLY, seqId); err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if _write_err5 != nil {
    return false, thrift.WrapTException(_write_err5)
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Task
type TaskManagerCreateArgs struct {
  Task *Task `thrift:"task,1" db:"task" json:"task"`
}

func NewTaskManagerCreateArgs() *TaskManagerCreateArgs {
  return &TaskManagerCreateArgs{}
}

var TaskManagerCreateArgs_Task_DEFAULT *Task
func (p *TaskManagerCreateArgs) GetTask() *Task {
  if !p.IsSetTask() {
    return TaskManagerCreateArgs_Task_DEFAULT
  }
return p.Task
}
func (p *TaskManagerCreateArgs) IsSetTask() bool {
  return p.Task != nil
}

func (p *TaskManagerCreateArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TaskManagerCreateArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Task = &Task{
  Identifier: -1,
}
  if err := p.Task.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Task), err)
  }
  return nil
}

func (p *TaskManagerCreateArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "create_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TaskManagerCreateArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "task", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:task: ", p), err) }
  if err := p.Task.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Task), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:task: ", p), err) }
  return err
}

func (p *TaskManagerCreateArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TaskManagerCreateArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - E
type TaskManagerCreateResult struct {
  Success *int64 `thrift:"success,0" db:"success" json:"success,omitempty"`
  E *TaskException `thrift:"e,1" db:"e" json:"e,omitempty"`
}

func NewTaskManagerCreateResult() *TaskManagerCreateResult {
  return &TaskManagerCreateResult{}
}

var TaskManagerCreateResult_Success_DEFAULT int64
func (p *TaskManagerCreateResult) GetSuccess() int64 {
  if !p.IsSetSuccess() {
    return TaskManagerCreateResult_Success_DEFAULT
  }
return *p.Success
}
var TaskManagerCreateResult_E_DEFAULT *TaskException
func (p *TaskManagerCreateResult) GetE() *TaskException {
  if !p.IsSetE() {
    return TaskManagerCreateResult_E_DEFAULT
  }
return p.E
}
func (p *TaskManagerCreateResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *TaskManagerCreateResult) IsSetE() bool {
  return p.E != nil
}

func (p *TaskManagerCreateResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField0(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TaskManagerCreateResult)  ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(ctx); err != nil {
  return thrift.PrependError("error reading field 0: ", err)
} else {
  p.Success = &v
}
  return nil
}

func (p *TaskManagerCreateResult)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.E = &TaskException{}
  if err := p.E.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.E), err)
  }
  return nil
}

func (p *TaskManagerCreateResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "create_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(ctx, oprot); err != nil { return err }
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TaskManagerCreateResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin(ctx, "success", thrift.I64, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := oprot.WriteI64(ctx, int64(*p.Success)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.success (0) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *TaskManagerCreateResult) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetE() {
    if err := oprot.WriteFieldBegin(ctx, "e", thrift.STRUCT, 1); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:e: ", p), err) }
    if err := p.E.Write(ctx, oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.E), err)
    }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 1:e: ", p), err) }
  }
  return err
}

func (p *TaskManagerCreateResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TaskManagerCreateResult(%+v)", *p)
}


